sudo: false

language: python

python:
  - 3.6
  - 2.7

install:
  - pip install .
  - pip install coverage
  - pip install codecov

script:
  - coverage run tests/tests_client.py

after_success:
  - codecov
